from typing import List, Optional
from pydantic import BaseModel, Field
from datetime import datetime
from decimal import Decimal

# --- AI Schema Alignment Models ---
class ColumnMapping(BaseModel):
    target_primitive: str = Field(
        ..., 
        description="Target system primitive, must be one of: 'transaction_id', 'amount', 'timestamp', or 'metadata'"
    )
    raw_field_name: str = Field(
        ..., 
        description="The header or column name in the source file that maps to this primitive"
    )
    inferred_format: Optional[str] = Field(
        None, 
        description="Format description of the source column, e.g., 'Alphanumeric String', 'String Numeric (150.25)', 'ISO-8601 String'"
    )
    confidence: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="Confidence score for this column alignment"
    )
    rationale: str = Field(
        ..., 
        description="Contextual mapping logic and explanation of why this raw column matches the primitive"
    )

class SchemaAlignmentPayload(BaseModel):
    mappings: List[ColumnMapping] = Field(
        ..., 
        description="Bidirectional column mappings generated by context evaluation"
    )
    overall_confidence: float = Field(
        ..., 
        ge=0.0, 
        le=1.0, 
        description="Overall confidence score for the schema alignment"
    )

# --- Normalized Transaction Models for ingestion ---
class NormalizedTransaction(BaseModel):
    bank_name: str = Field(..., example="Chase Enterprise")
    agent_name: str = Field(..., example="ACH_Processor_v2")
    transaction_id: str = Field(..., example="TX_2026_001")
    amount: Decimal = Field(..., example=Decimal("150.25"))
    transaction_date: str = Field(..., example="2026-06-07")
    timestamp: datetime = Field(..., example="2026-06-07T10:24:31Z")
    status: str = Field("UNRECONCILED", example="MATCHED")
    matching_checksum: Optional[str] = Field(None, example="8f3c7b...")

    model_config = {
        "json_encoders": {
            Decimal: lambda v: str(v)
        }
    }
